import {Building} from "./Types";

export const requestTime = 1000


export const iIndicatorsMock:Building[] = [
    // {
    //     id: 1,
    //     name: "Электроэнергия",
    //     status: 1,
    //     description: "Электроэнергия это — физический термин, широко распространённый в технике и в быту для определения количества электрической энергии, выдаваемой генератором в электрическую сеть или получаемой из сети потребителем.",
    //     image: "",
    //     type: "кВт.ч",
    // },
    // {
    //     id: 2,
    //     name: "Отопление",
    //     status: 1,
    //     description: "Отопление это — искусственный обогрев помещений с целью возмещения в них теплопотерь и поддержания на заданном уровне температуры, отвечающей условиям теплового комфорта и/или требованиям технологического процесса.",
    //     image: "",
    //     type: "ГКал",
    // },
    // {
    //     id: 3,
    //     name: "Холодное водоснабжение",
    //     status: 1,
    //     description: "Холодное водоснабжение это — круглосуточное обеспечение потребителя холодной питьевой водой надлежащего качества, подаваемой в необходимых объемах по присоединенной сети в жилое помещение либо до водоразборной колонки.",
    //     image: "",
    //     type: "м3",
    // },


    {
        building_id: 1,
        title: "Научно-образовательный корпус",
        address: "2-я Бауманская улица, 7с1",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 2,
        title: "Квантум парк",
        address: "Бригадирский переулок, 13с4",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 3,
        title: "Дом РФ",
        address: "Бригадирский переулок, 12с1",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 4,
        title: "Образовательный комплекс",
        address: "Бригадирский переулок, 13",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 5,
        title: "Библиотечный корпус",
        address: "2-я Бауманская улица, 10",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 6,
        title: "Дворец технологий",
        address: "Бауманская улица, 57Ас1",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 7,
        title: "Центр биомедицинских систем и технологий",
        address: "Бригадирский переулок, 12",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 8,
        title: "Комплекс общежитий",
        address: "55.771550, 37.695786",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
    {
        building_id: 9,
        title: "Образовательно-досуговый центр Спектр",
        address: "55.771777, 37.695370",
        type_building: "Общественный",
        document_building: "Да",
        project_document: "Да",
        status: 1,
        image: "",
    },
]